# Generated by Django 5.1.3 on 2025-04-06 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_workschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='myapp.student'),
        ),
    ]
