# Generated by Django 5.1.3 on 2025-04-07 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_dailyworkreport_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyevaluation',
            name='month_number',
            field=models.PositiveIntegerField(blank=True, help_text='Sequential month number in the internship', null=True, verbose_name='Month Sequence Number'),
        ),
        migrations.AddField(
            model_name='monthlyevaluation',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='myapp.workschedule'),
        ),
    ]
