# Generated by Django 5.1.3 on 2025-04-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_internship_options_remove_internship_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='optional_qualifications',
            field=models.JSONField(default=list, help_text='List of optional qualifications for the internship.'),
        ),
        migrations.AddField(
            model_name='internship',
            name='required_qualifications',
            field=models.JSONField(default=list, help_text='List of qualifications required for the internship.'),
        ),
    ]
