# Generated by Django 5.1.3 on 2025-04-08 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_monthlyevaluation_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyevaluation',
            name='team_quality',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
