# Generated by Django 5.1.3 on 2025-04-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_task_communication_task_punctuality_task_quality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='communication',
        ),
        migrations.RemoveField(
            model_name='task',
            name='punctuality',
        ),
        migrations.RemoveField(
            model_name='task',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reliability',
        ),
    ]
