# Generated by Django 5.1.3 on 2025-04-13 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_task_communication_remove_task_punctuality_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internship',
            options={},
        ),
        migrations.RemoveField(
            model_name='internship',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='start_date',
        ),
        migrations.AddField(
            model_name='internship',
            name='duration',
            field=models.CharField(choices=[('1', '1 Month'), ('2', '2 Months'), ('3', '3 Months'), ('6', '6 Months'), ('12', '1 Year')], default='3', max_length=3),
        ),
        migrations.AddField(
            model_name='internship',
            name='training_format',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('project_based', 'Project-based')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='internship',
            name='training_types',
            field=models.JSONField(default=list, help_text="List the specific training types (e.g., ['CCNA Certification', 'Python Programming', 'Cloud Security'])"),
        ),
        migrations.AlterField(
            model_name='internship',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='internship',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
